# Generated by Django 3.1.6 on 2021-02-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_ordermodel_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_shift',
            field=models.BooleanField(default=False),
        ),
    ]
