# Generated by Django 3.1.6 on 2021-02-17 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_ordermodel_is_shift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='is_shift',
            new_name='is_shipped',
        ),
    ]
